### ISSUE TITLE
tf_nn error while running

### ISSUE THREAD

**Issue by saquibntt** [jorisvanmens/speech_emotion_recognition#2]
Traceback (most recent call last):
  File "tf_nn.py", line 74, in <module>
    labelIndex = getFeatureIndices([u"emotion"])[0]
  File "tf_nn.py", line 62, in getFeatureIndices
    featureIndices.append([index for index, feature in enumerate(featuresData['attributes']) if feature[0] == featureName][0])
TypeError: 'generator' object is not subscriptable

**Comment by saquibntt** [comment]
No issues in linux machine
